CREATE TABLE IF NOT EXISTS auth.users (
    instance_id uuid,
    id uuid PRIMARY KEY,
    aud varchar,
    role varchar,
    email varchar,
    encrypted_password varchar,
    email_confirmed_at timestamptz,
    invited_at timestamptz,
    confirmation_token varchar,
    confirmation_sent_at timestamptz,
    recovery_token varchar,
    recovery_sent_at timestamptz,
    email_change_token_new varchar,
    email_change varchar,
    email_change_sent_at timestamptz,
    last_sign_in_at timestamptz,
    raw_app_meta_data jsonb,
    raw_user_meta_data jsonb,
    is_super_admin boolean,
    created_at timestamptz,
    updated_at timestamptz,
    phone text UNIQUE,
    phone_confirmed_at timestamptz,
    phone_change varchar DEFAULT ''::varchar,
    phone_change_token varchar DEFAULT ''::varchar,
    phone_change_sent_at timestamptz,
    confirmed_at timestamptz GENERATED ALWAYS AS (LEAST(email_confirmed_at, phone_confirmed_at)) STORED,
    email_change_token_current varchar DEFAULT ''::varchar,
    email_change_confirm_status smallint DEFAULT 0 CHECK (email_change_confirm_status >= 0 AND email_change_confirm_status <= 2),
    banned_until timestamptz,
    reauthentication_token varchar DEFAULT ''::varchar,
    reauthentication_sent_at timestamptz,
    is_sso_user boolean NOT NULL DEFAULT false,
    deleted_at timestamptz
);
